
const D=window.NEXUS_DATA;
let S=JSON.parse(localStorage.getItem("nexus-v3")||'{"selected":"A","weight":75,"meals":[],"insulin":{},"sets":{},"glucose":[],"workouts":[]}'),trend="→";
const save=()=>localStorage.setItem("nexus-v3",JSON.stringify(S));
function go(id){document.querySelectorAll(".screen").forEach(s=>s.classList.toggle("on",s.id===id));document.querySelectorAll("[data-view]").forEach(b=>b.classList.toggle("on",b.dataset.view===id));window.scrollTo(0,0);if(id==="home")home();if(id==="glucose")glucose();if(id==="diet")diet();if(id==="subs")subs();if(id==="workout"){days();workout();}if(id==="history")history();}
document.querySelectorAll("[data-view]").forEach(b=>b.onclick=()=>go(b.dataset.view));document.querySelectorAll("[data-go]").forEach(b=>b.onclick=()=>go(b.dataset.go));
function home(){let g=S.glucose.at(-1),a=S.glucose.map(x=>x.value),cal=S.meals.reduce((t,i)=>t+(D.meals.find(m=>m.id===i)?.kcal||0),0);document.getElementById("homeCal").textContent=cal;document.getElementById("homeBar").style.width=Math.min(cal/3400*100,100)+"%";document.getElementById("homeWMeta").textContent=`Treino ${S.selected} · ${D.workouts[S.selected].title}`;if(g){document.getElementById("homeGVal").textContent=g.value+" mg/dL";document.getElementById("homeGBig").textContent=g.value+" mg/dL";document.getElementById("homeGArrow").textContent=g.trend;document.getElementById("homeGMeta").textContent=g.context+" · "+g.time;document.getElementById("homeGState").textContent=g.context+" · tendência "+g.trend;document.getElementById("hAvg").textContent=Math.round(a.reduce((x,y)=>x+y,0)/a.length);document.getElementById("hMax").textContent=Math.max(...a);document.getElementById("hMin").textContent=Math.min(...a);document.getElementById("hTarget").textContent=Math.round(a.filter(x=>x>=70&&x<=180).length/a.length*100)+"%";}}
function glucose(){let r=[...S.glucose].reverse(),g=r[0];document.getElementById("gCount").textContent=r.length;if(g){document.getElementById("gCurrent").textContent=g.value+" mg/dL";document.getElementById("gCurrentArrow").textContent=g.trend;document.getElementById("gCurrentMeta").textContent=g.context+" · "+g.time;}document.getElementById("gList").innerHTML=r.map(x=>`<div class="mini"><div class="miniIcon ${x.value<70?'redbg':x.value>250?'orangebg':'greenbg'}">◉</div><div class="miniMain"><b>${x.value} mg/dL ${x.trend}</b><span>${x.context} · ${x.time}${x.note?" · "+x.note:""}</span></div><span>›</span></div>`).join("")||`<div class="muted" style="padding:8px 0">Nenhuma aferição.</div>`;}
document.querySelectorAll("[data-tr]").forEach(b=>b.onclick=()=>{trend=b.dataset.tr;document.querySelectorAll("[data-tr]").forEach(x=>x.classList.toggle("on",x===b));});
document.getElementById("addG").onclick=()=>{let v=parseInt(document.getElementById("gVal").value,10);if(!v)return alert("Informe a glicemia.");let n=new Date();S.glucose.push({value:v,context:document.getElementById("gCtx").value,trend,note:document.getElementById("gNote").value,time:n.toLocaleTimeString("pt-BR",{hour:"2-digit",minute:"2-digit"})});save();document.getElementById("gVal").value="";document.getElementById("gNote").value="";glucose();home();};
function diet(){let total=0;document.getElementById("mealList").innerHTML=D.meals.map(m=>{let ok=S.meals.includes(m.id);if(ok)total+=m.kcal;let ins=S.insulin[m.id]||"";return `<div class="meal"><div class="mealTop"><div class="mealPic">${m.icon}</div><div class="mealMain"><b>${m.time} · ${m.name}</b><span>${m.items.slice(0,3).map(x=>x[0]+" "+x[1]).join(" · ")}${m.items.length>3?" · ...":""}</span><span class="mealKcal">~${m.kcal} kcal</span></div></div>${m.items.map(f=>`<div class="foodrow"><b>${f[0]}</b><span>${f[1]}</span></div><div class="actions"><button data-sub="${f[2]}" data-name="${f[0]}">5 substituições</button></div>`).join("")}<div class="insRow"><span class="unit">Insulina aplicada</span><input data-ins="${m.id}" type="number" step=".5" inputmode="decimal" placeholder="Registrar U" value="${ins}"><span class="unit">U</span></div><div class="actions"><button data-meal="${m.id}" class="${ok?"done":""}" style="width:100%">${ok?"✓ Refeição consumida":"Marcar como consumida"}</button></div></div>`}).join("");document.getElementById("dietCal").textContent=total;document.querySelectorAll("[data-meal]").forEach(b=>b.onclick=()=>{let id=b.dataset.meal;S.meals.includes(id)?S.meals=S.meals.filter(x=>x!==id):S.meals.push(id);save();diet();home();});document.querySelectorAll("[data-ins]").forEach(i=>i.oninput=()=>{S.insulin[i.dataset.ins]=i.value;save();});document.querySelectorAll("[data-sub]").forEach(b=>b.onclick=()=>openSubs(b.dataset.sub,b.dataset.name));}
function subs(){let q=(document.getElementById("subSearch").value||"").toLowerCase();let html="";Object.entries(D.subs).forEach(([k,list])=>{if(!q||k.includes(q)||({"banana":"Banana","aveia":"Aveia","leite":"Leite","pasta":"Pasta de amendoim","ovos":"Ovos","pao":"Pão","queijo":"Queijo","iogurte":"Iogurte","arroz":"Arroz","feijao":"Feijão","frango":"Frango","salada":"Salada","whey":"Whey"}[k]||"").toLowerCase().includes(q)){let label={"banana":"Banana","aveia":"Aveia","leite":"Leite","pasta":"Pasta de amendoim","ovos":"Ovos","pao":"Pão","queijo":"Queijo","iogurte":"Iogurte","arroz":"Arroz","feijao":"Feijão","frango":"Frango","salada":"Salada","whey":"Whey"}[k]||k;html+=`<div class="subGroup"><div class="subHead"><span class="h2" style="font-size:11px">${label}</span><span class="badge">5 opções</span></div>${list.map((x,i)=>`<div class="subRow"><b>${i+1}. ${x[0]}</b><span>${x[1]}</span></div>`).join("")}</div>`;}});document.getElementById("subList").innerHTML=html||`<div class="muted">Nenhum alimento encontrado.</div>`;}
document.getElementById("subSearch").oninput=subs;
function openSubs(k,n){go("subs");document.getElementById("subSearch").value=n;subs();}
function days(){document.getElementById("dayList").innerHTML=[["A","Seg"],["B","Ter"],["C","Qua"],["D","Qui"],["E","Sex"]].map(x=>`<button class="day ${S.selected===x[0]?'on':''}" data-day="${x[0]}">${x[0]}<br>${x[1]}</button>`).join("");document.querySelectorAll("[data-day]").forEach(b=>b.onclick=()=>{S.selected=b.dataset.day;save();days();workout();home();});}
function workout(){const w=D.workouts[S.selected];document.getElementById("workoutList").innerHTML=`<div class="card"><div class="row"><span class="h2">Treino ${S.selected} — ${w.title}</span><span class="badge">${w.ex.reduce((a,e)=>a+e[1],0)} séries</span></div>${w.ex.map((e,ei)=>{let z="";for(let si=0;si<e[1];si++){let k=S.selected+"-"+ei+"-"+si,v=S.sets[k]||{};z+=`<div class="set ${v.done?'done':''}" data-k="${k}"><small>S${si+1}</small><input class="kg" type="number" step=".5" placeholder="kg" value="${v.kg||''}"><input class="reps" type="number" placeholder="reps" value="${v.reps||''}"><button class="toggle">${v.done?'✓':'○'}</button></div>`}return `<div class="ex"><div class="exTop"><img class="exImg" src="${e[3]}"><div><div class="exName">${e[0]}</div><div class="exmeta muted">${e[2]}</div><span class="tag">${e[4]}</span><span class="tag blue">${e[5]}</span><br><button class="ref" data-ref="${e[3]}" data-title="${e[0]}">Ver referência</button></div></div><div class="sets">${z}</div></div>`}).join("")}</div>`;document.querySelectorAll(".set input").forEach(i=>i.oninput=()=>{let k=i.parentElement.dataset.k;S.sets[k]=S.sets[k]||{};S.sets[k][i.classList.contains("kg")?"kg":"reps"]=i.value;save();});document.querySelectorAll(".toggle").forEach(b=>b.onclick=()=>{let k=b.parentElement.dataset.k;S.sets[k]=S.sets[k]||{};S.sets[k].done=!S.sets[k].done;save();workout();});document.querySelectorAll(".ref").forEach(b=>b.onclick=()=>openRef(b.dataset.ref,b.dataset.title));}
function openRef(ref,title){document.getElementById("mTitle").textContent=title;document.getElementById("mImg").src=ref;document.getElementById("mImg").style.display="block";document.getElementById("mText").textContent="Imagem de referência do movimento.";document.getElementById("modal").style.display="flex";}
document.getElementById("finishWorkout").onclick=()=>{S.workouts.push({workout:S.selected,date:new Date().toLocaleDateString("pt-BR"),rpe:document.getElementById("rpe").value});save();document.getElementById("wSaved").style.display="block";history();};
function history(){document.getElementById("trainCount").textContent=S.workouts.length;document.getElementById("hist").innerHTML=[...S.glucose].reverse().slice(0,10).map(x=>`<div class="hist"><b>Glicemia · ${x.value} mg/dL ${x.trend}</b><small>${x.context} · ${x.time}</small></div>`).join("")||`<div class="muted">Sem registros.</div>`;}
document.getElementById("close").onclick=()=>document.getElementById("modal").style.display="none";document.getElementById("close2").onclick=()=>document.getElementById("modal").style.display="none";
init();function init(){days();workout();diet();glucose();subs();history();home();if("serviceWorker"in navigator)navigator.serviceWorker.register("sw.js");}
