
const D=window.NEXUS_DATA;
let S=JSON.parse(localStorage.getItem("nexus-v4")||'{"sel":"A","weight":75,"meals":[],"insulin":{},"sets":{},"glucose":[],"workouts":[],"shopping":[]}');
let trend="→";
const save=()=>localStorage.setItem("nexus-v4",JSON.stringify(S));
const go=(id)=>{document.querySelectorAll(".screen").forEach(x=>x.classList.toggle("on",x.id===id));document.querySelectorAll("[data-view]").forEach(x=>x.classList.toggle("on",x.dataset.view===id));window.scrollTo(0,0);if(id==="home")home();if(id==="glucose")glucose();if(id==="diet")diet();if(id==="subs")subs();if(id==="shopping")shopping();if(id==="workout"){days();workout();}if(id==="history")history();};
document.querySelectorAll("[data-view]").forEach(x=>x.onclick=()=>go(x.dataset.view));document.querySelectorAll("[data-go]").forEach(x=>x.onclick=()=>go(x.dataset.go));
function home(){let g=S.glucose.at(-1),a=S.glucose.map(x=>x.value),cal=S.meals.reduce((t,id)=>t+(D.meals.find(m=>m.id===id)?.kcal||0),0);document.getElementById("homeCal").textContent=cal;document.getElementById("homeBar").style.width=Math.min(cal/5000*100,100)+"%";document.getElementById("homeWMeta").textContent=`Treino ${S.sel} · ${D.workouts[S.sel].title}`;if(g){document.getElementById("homeGVal").textContent=g.value+" mg/dL";document.getElementById("homeGBig").textContent=g.value+" mg/dL";document.getElementById("homeGArrow").textContent=g.trend;document.getElementById("homeGMeta").textContent=g.context+" · "+g.time;document.getElementById("homeGState").textContent=g.context+" · tendência "+g.trend;document.getElementById("homeAvg").textContent=Math.round(a.reduce((x,y)=>x+y,0)/a.length);document.getElementById("homeMax").textContent=Math.max(...a);document.getElementById("homeMin").textContent=Math.min(...a);document.getElementById("homeTarget").textContent=Math.round(a.filter(x=>x>=70&&x<=180).length/a.length*100)+"%";}};
function glucose(){let r=[...S.glucose].reverse(),g=r[0];document.getElementById("gCount").textContent=r.length;if(g){document.getElementById("gCurrent").textContent=g.value+" mg/dL";document.getElementById("gArrow").textContent=g.trend;document.getElementById("gMeta").textContent=g.context+" · "+g.time;}document.getElementById("gList").innerHTML=r.map(x=>`<div class="mini"><div class="mini-icon ${x.value<70?'redbg':x.value>250?'orangebg':'greenbg'}">◉</div><div class="mini-main"><b>${x.value} mg/dL ${x.trend}</b><span>${x.context} · ${x.time}${x.note?" · "+x.note:""}</span></div><span>›</span></div>`).join("")||`<div class="muted" style="padding:8px 0">Nenhuma aferição.</div>`;}
document.querySelectorAll("[data-tr]").forEach(x=>x.onclick=()=>{trend=x.dataset.tr;document.querySelectorAll("[data-tr]").forEach(b=>{b.classList.toggle("on",b===x);b.style.background=b===x?"var(--red)":"#202932";});});
document.getElementById("addG").onclick=()=>{let v=parseInt(document.getElementById("gVal").value,10);if(!v)return alert("Informe a glicemia.");let n=new Date();S.glucose.push({value:v,context:document.getElementById("gCtx").value,trend,note:document.getElementById("gNote").value,time:n.toLocaleTimeString("pt-BR",{hour:"2-digit",minute:"2-digit"})});save();document.getElementById("gVal").value="";document.getElementById("gNote").value="";glucose();home();};
function diet(){let total=0;document.getElementById("mealList").innerHTML=D.meals.map(m=>{let ok=S.meals.includes(m.id);if(ok)total+=m.kcal;let img={"Pré-treino":"food-banana.svg","Café da manhã":"food-eggs.svg","Lanche":"food-oats.svg","Almoço":"food-rice.svg","Lanche da tarde":"food-bread.svg","Jantar":"food-chicken.svg","Ceia (Shake calórico)":"food-shake.svg"}[m.name]||"food-rice.svg";let ins=S.insulin[m.id]||"";return `<div class="meal"><div class="meal-head"><img class="food-img" src="${img}"><div class="meal-info"><b>${m.time} · ${m.name}</b><span>${m.items.slice(0,3).map(x=>x[0]+" "+x[1]).join(" · ")}${m.items.length>3?" · ...":""}</span><span class="kcal">~${m.kcal} kcal</span></div></div><div class="meal-list">${m.items.map(f=>`<div class="food-row"><span class="food-name">${f[0]}</span><span class="food-qty">${f[1]}</span><button class="sub-btn" data-sub="${f[2]}" data-name="${f[0]}">Substituir</button></div>`).join("")}</div><div class="ins"><span>Insulina aplicada</span><input data-ins="${m.id}" type="number" step=".5" inputmode="decimal" placeholder="Registrar U" value="${ins}"><span>U</span></div><button class="meal-done ${ok?'done':''}" data-meal="${m.id}">${ok?"✓ Refeição consumida":"Marcar como consumida"}</button></div>`}).join("");document.getElementById("homeCal").textContent=total;document.querySelectorAll("[data-meal]").forEach(b=>b.onclick=()=>{let id=b.dataset.meal;S.meals.includes(id)?S.meals=S.meals.filter(x=>x!==id):S.meals.push(id);save();diet();home();});document.querySelectorAll("[data-ins]").forEach(i=>i.oninput=()=>{S.insulin[i.dataset.ins]=i.value;save();});document.querySelectorAll("[data-sub]").forEach(b=>b.onclick=()=>openSubs(b.dataset.sub,b.dataset.name));}
function subs(){let q=(document.getElementById("subSearch")?.value||"").toLowerCase();let labels={banana:"Banana",aveia:"Aveia",leite:"Leite",pasta:"Pasta de amendoim",ovos:"Ovos",pao:"Pão",queijo:"Queijo",iogurte:"Iogurte",arroz:"Arroz",feijao:"Feijão",frango:"Frango",salada:"Salada",whey:"Whey"};let h="";Object.entries(D.subs).forEach(([k,list])=>{let label=labels[k]||k;if(!q||label.toLowerCase().includes(q)||k.includes(q))h+=`<div class="sub-group"><div class="sub-head"><span class="h2" style="font-size:11px">${label}</span><span class="badge">5 opções</span></div>${list.map((x,i)=>`<div class="sub-row"><b>${i+1}. ${x[0]}</b><span>${x[1]}</span></div>`).join("")}</div>`});document.getElementById("subList").innerHTML=h||`<div class="muted">Nenhum alimento encontrado.</div>`;}
document.getElementById("subSearch").oninput=subs;
function openSubs(k,n){go("subs");document.getElementById("subSearch").value=n;subs();}
function shopping(){let items=[["Banana","8 unidades","food-banana.svg"],["Aveia","500 g","food-oats.svg"],["Leite integral","4 litros","food-shake.svg"],["Ovos","30 unidades","food-eggs.svg"],["Arroz","3 kg","food-rice.svg"],["Frango","2 kg","food-chicken.svg"],["Pão","2 pacotes","food-bread.svg"],["Pasta de amendoim","500 g","food-shake.svg"],["Whey","1 pacote","food-shake.svg"],["Lentilha","1 kg","food-rice.svg"]];let checked=S.shopping||[];document.getElementById("buyCount").textContent=items.length+" itens";document.getElementById("shoppingList").innerHTML=items.map((x,i)=>`<div class="list-row"><img src="${x[2]}"><div class="list-main"><b>${x[0]}</b><span>${x[1]}</span></div><button class="check ${checked.includes(i)?'on':''}" data-buy="${i}">${checked.includes(i)?"✓":""}</button></div>`).join("");document.querySelectorAll("[data-buy]").forEach(b=>b.onclick=()=>{let i=+b.dataset.buy;S.shopping=checked.includes(i)?checked.filter(x=>x!==i):[...checked,i];save();shopping();});}
function days(){document.getElementById("dayList").innerHTML=[["A","Seg"],["B","Ter"],["C","Qua"],["D","Qui"],["E","Sex"]].map(x=>`<button class="day ${S.sel===x[0]?'on':''}" data-day="${x[0]}">${x[0]}<br>${x[1]}</button>`).join("");document.querySelectorAll("[data-day]").forEach(b=>b.onclick=()=>{S.sel=b.dataset.day;save();days();workout();home();});}
function workout(){let w=D.workouts[S.sel];document.getElementById("workoutList").innerHTML=`<div class="card"><div class="row"><span class="h2">Treino ${S.sel} — ${w.title}</span><span class="badge">${w.ex.reduce((a,e)=>a+e[1],0)} séries</span></div>${w.ex.map((e,ei)=>{let z="";for(let si=0;si<e[1];si++){let k=S.sel+"-"+ei+"-"+si,v=S.sets[k]||{};z+=`<div class="set ${v.done?'done':''}" data-k="${k}"><small>S${si+1}</small><input class="kg" type="number" step=".5" inputmode="decimal" placeholder="kg" value="${v.kg||''}"><input class="reps" type="number" inputmode="numeric" placeholder="reps" value="${v.reps||''}"><button class="toggle">${v.done?'✓':'○'}</button></div>`}return `<div class="ex"><div class="ex-top"><img class="ex-img" src="${e[3]}"><div><div class="ex-name">${e[0]}</div><div class="ex-meta">${e[2]}</div><span class="tag">${e[4]}</span><span class="tag blue">${e[5]}</span><div class="ex-buttons"><button data-ref="${e[3]}" data-title="${e[0]}">Ver execução</button><button data-ref="${e[3]}" data-title="${e[0]}">Imagem</button></div></div></div><div class="sets">${z}</div></div>`}).join("")}</div>`;document.querySelectorAll(".set input").forEach(i=>i.oninput=()=>{let k=i.parentElement.dataset.k;S.sets[k]=S.sets[k]||{};S.sets[k][i.classList.contains("kg")?"kg":"reps"]=i.value;save();});document.querySelectorAll(".toggle").forEach(b=>b.onclick=()=>{let k=b.parentElement.dataset.k;S.sets[k]=S.sets[k]||{};S.sets[k].done=!S.sets[k].done;save();workout();});document.querySelectorAll("[data-ref]").forEach(b=>b.onclick=()=>openRef(b.dataset.ref,b.dataset.title));}
function openRef(ref,title){document.getElementById("mTitle").textContent=title;document.getElementById("mImg").src=""+ref;document.getElementById("mText").innerHTML=`<b>Execução</b><ol>${(D.execution?.[ref]||["Execute o movimento com controle.","Mantenha a postura estável.","Use amplitude adequada.","Finalize a repetição sem perder o controle."]).map(x=>`<li>${x}</li>`).join("")}</ol>`;document.getElementById("modal").style.display="flex";}
function history(){document.getElementById("trainCount").textContent=S.workouts.length;document.getElementById("hist").innerHTML=[...S.glucose].reverse().slice(0,10).map(x=>`<div class="history-row"><b>Glicemia · ${x.value} mg/dL ${x.trend}</b><small>${x.context} · ${x.time}</small></div>`).join("")||`<div class="muted">Sem registros.</div>`;}
document.getElementById("finishW").onclick=()=>{S.workouts.push({workout:S.sel,date:new Date().toLocaleDateString("pt-BR"),rpe:document.getElementById("rpe").value});save();document.getElementById("wOk").style.display="block";history();};
document.getElementById("mClose").onclick=()=>document.getElementById("modal").style.display="none";document.getElementById("mClose2").onclick=()=>document.getElementById("modal").style.display="none";
init();function init(){days();workout();diet();glucose();subs();shopping();history();home();if("serviceWorker"in navigator)navigator.serviceWorker.register("sw.js");}
