
const D=window.NEXUS_DATA;
let S=JSON.parse(localStorage.getItem("nexus-v2")||'{"sel":"B","weight":75,"meals":[],"insulin":{},"sets":{},"glucose":[],"workouts":[]}'),trend="→";
const save=()=>localStorage.setItem("nexus-v2",JSON.stringify(S));
function go(id){document.querySelectorAll(".view").forEach(v=>v.classList.toggle("on",v.id===id));document.querySelectorAll("[data-view]").forEach(b=>b.classList.toggle("on",b.dataset.view===id));window.scrollTo(0,0);if(id==="home")home();if(id==="glucose")glucose();if(id==="diet")diet();if(id==="subs")subs();if(id==="workout"){days();workout();}if(id==="history")history();}
document.querySelectorAll("[data-view]").forEach(b=>b.onclick=()=>go(b.dataset.view));document.querySelectorAll("[data-go]").forEach(b=>b.onclick=()=>go(b.dataset.go));
function home(){let g=S.glucose.at(-1),a=S.glucose.map(x=>x.value),cal=S.meals.reduce((t,i)=>t+(D.meals.find(m=>m[0]===i)?.[3]||0),0);document.getElementById("hWeight").textContent=Number(S.weight||75).toFixed(1).replace(".",",");document.getElementById("hCal").textContent=cal;document.getElementById("hBar").style.width=Math.min(cal/3400*100,100)+"%";document.getElementById("hWMeta").textContent=`Treino ${S.sel} · ${D.workouts[S.sel][0]}`;if(g){["hGVal","hGBig"].forEach(id=>document.getElementById(id).textContent=g.value+" mg/dL");document.getElementById("hGMeta").textContent=g.context+" · "+g.time;document.getElementById("hGArrow").textContent=g.trend;document.getElementById("hGState").textContent=g.context+" · tendência "+g.trend;document.getElementById("hAvg").textContent=Math.round(a.reduce((x,y)=>x+y,0)/a.length);document.getElementById("hMax").textContent=Math.max(...a);document.getElementById("hMin").textContent=Math.min(...a);}}
function glucose(){const r=[...S.glucose].reverse(),g=r[0];document.getElementById("gCount").textContent=r.length;if(g){document.getElementById("gCurrent").textContent=g.value+" mg/dL";document.getElementById("gArrow").textContent=g.trend;document.getElementById("gMeta").textContent=g.context+" · "+g.time;}document.getElementById("gList").innerHTML=r.map(x=>`<div class="g-row"><div class="dot ${x.value<70?"bad":(x.value<90||x.value>250?"warn":"")}"></div><div class="g-main"><div class="g-val">${x.value} mg/dL ${x.trend}</div><div class="g-meta">${x.context} · ${x.time}${x.note?" · "+x.note:""}</div></div></div>`).join("")||`<div class="muted" style="padding:8px 0">Nenhuma aferição.</div>`}
document.querySelectorAll("[data-tr]").forEach(b=>b.onclick=()=>{trend=b.dataset.tr;document.querySelectorAll("[data-tr]").forEach(x=>x.classList.toggle("on",x===b));});
document.getElementById("addG").onclick=()=>{let v=parseInt(document.getElementById("gVal").value,10);if(!v)return alert("Informe a glicemia.");let n=new Date();S.glucose.push({value:v,context:document.getElementById("gCtx").value,trend,note:document.getElementById("gNote").value,time:n.toLocaleTimeString("pt-BR",{hour:"2-digit",minute:"2-digit"})});save();document.getElementById("gVal").value="";document.getElementById("gNote").value="";glucose();home();};
function diet(){let total=0,c=S.meals;document.getElementById("meals").innerHTML=D.meals.map(m=>{let ok=c.includes(m[0]);if(ok)total+=m[3];let ins=S.insulin[m[0]]||"";return `<div class="meal"><div class="meal-top"><div class="meal-pic">${m[4]}</div><div class="meal-main"><b>${m[1]} — ${m[2]}</b><span>${m[4]?m[4]:""} ${m[4]&&""}</span><span>${m[4]?m[4]:""}</span><span>${m[4]?m[4]:""}</span><span class="kcal">~${m[3]} kcal</span></div></div>${m[4]&&m[4] instanceof Array?m[4].map(f=>`<div style="margin-top:6px"><div class="row"><span class="meal-main" style="font-size:10px">${f[0]}</span><span class="muted">${f[1]}</span></div><div class="actions"><button data-sub="${f[2]}" data-name="${f[0]}">5 substituições</button></div></div>`).join(""):""}<div class="insulin"><span class="unit">Insulina aplicada</span><input data-ins="${m[0]}" type="number" step=".5" inputmode="decimal" placeholder="Registrar U" value="${ins}"><span class="unit">U</span></div><div class="actions"><button class="${ok?"done":""}" data-meal="${m[0]}" style="width:100%">${ok?"✓ Refeição consumida":"Marcar como consumida"}</button></div></div>`}).join("");document.getElementById("dietCal").textContent=total;document.querySelectorAll("[data-meal]").forEach(b=>b.onclick=()=>{let i=+b.dataset.meal;if(S.meals.includes(i))S.meals=S.meals.filter(x=>x!==i);else S.meals.push(i);save();diet();home();});document.querySelectorAll("[data-ins]").forEach(i=>i.oninput=()=>{S.insulin[i.dataset.ins]=i.value;save();});document.querySelectorAll("[data-sub]").forEach(b=>b.onclick=()=>openSubs(b.dataset.sub,b.dataset.name));}
function subs(){const q=(document.getElementById("subSearch")?.value||"").toLowerCase();let all=[];Object.keys(D.subs).forEach(k=>{if(!q||k.includes(q)){let label={banana:"Banana",aveia:"Aveia",leite:"Leite",pasta:"Pasta de amendoim",ovos:"Ovos",pao:"Pão",queijo:"Queijo",iogurte:"Iogurte",arroz:"Arroz",feijao:"Feijão",frango:"Frango",salada:"Salada",azeite:"Azeite",whey:"Whey"}[k]||k;all.push(`<div class="sub-group"><div class="row"><span class="h2" style="font-size:11px">${label}</span><span class="badge">5 opções</span></div>${D.subs[k].map((x,i)=>{let p=x.split(" — ");return `<div class="sub-row"><b>${i+1}. ${p[0]}</b><span>${p[1]||""}</span></div>`}).join("")}</div>`);}});document.getElementById("subList").innerHTML=all.join("");}
document.getElementById("subSearch")?.addEventListener("input",subs);
function openSubs(k,name){go("subs");document.getElementById("subSearch").value=name;subs();}
function days(){document.getElementById("days").innerHTML=[["A","Seg"],["B","Ter"],["C","Qua"],["D","Qui"],["E","Sex"]].map(x=>`<button class="daytab ${S.sel===x[0]?"on":""}" data-day="${x[0]}">Treino ${x[0]}<br>${x[1]}</button>`).join("");document.querySelectorAll("[data-day]").forEach(b=>b.onclick=()=>{S.sel=b.dataset.day;save();days();workout();home();});}
function workout(){const w=D.workouts[S.sel];document.getElementById("workoutList").innerHTML=`<div class="card"><div class="row"><span class="h2">Treino ${S.sel} — ${w[0]}</span><span class="badge">${w[1].reduce((a,e)=>a+e[1],0)} séries</span></div>${w[1].map((e,ei)=>{let z="";for(let si=0;si<e[1];si++){let k=S.sel+"-"+ei+"-"+si,v=S.sets[k]||{};z+=`<div class="set ${v.done?"done":""}" data-k="${k}"><small>S${si+1}</small><input class="kg" type="number" step=".5" placeholder="kg" value="${v.kg||""}"><input class="reps" type="number" placeholder="reps" value="${v.reps||""}"><button class="toggle">${v.done?"✓":"○"}</button></div>`}return `<div class="exercise"><div class="exhead"><img class="thumb" src="${e[3]}.jpg"><div><div class="exname">${e[0]}</div><div class="exmeta">${e[1]} × ${e[2]}</div><button class="ref" data-ref="${e[3]}" data-title="${e[0]}">Ver referência</button></div></div><div class="sets">${z}</div></div>`}).join("")}</div>`;document.querySelectorAll(".set input").forEach(i=>i.oninput=()=>{let k=i.parentElement.dataset.k;S.sets[k]=S.sets[k]||{};S.sets[k][i.classList.contains("kg")?"kg":"reps"]=i.value;save();});document.querySelectorAll(".toggle").forEach(b=>b.onclick=()=>{let k=b.parentElement.dataset.k;S.sets[k]=S.sets[k]||{};S.sets[k].done=!S.sets[k].done;save();workout();});document.querySelectorAll(".ref").forEach(b=>b.onclick=()=>openRef(b.dataset.ref,b.dataset.title));}
function openRef(ref,title){document.getElementById("mTitle").textContent=title;document.getElementById("mImg").src=ref+".jpg";document.getElementById("mImg").style.display="block";document.getElementById("mText").textContent="Referência visual do movimento.";document.getElementById("modal").style.display="flex";}
document.getElementById("saveW").onclick=()=>{S.workouts.push({workout:S.sel,date:new Date().toLocaleDateString("pt-BR"),rpe:document.getElementById("rpe").value});save();document.getElementById("wOk").style.display="block";history();};
function history(){document.getElementById("hTrain").textContent=S.workouts.length;document.getElementById("histList").innerHTML=[...S.glucose].reverse().slice(0,12).map(x=>`<div class="history-row"><b>Glicemia · ${x.value} mg/dL ${x.trend}</b><small>${x.context} · ${x.time}</small></div>`).join("")||`<div class="muted">Sem registros.</div>`;}
document.getElementById("mClose").onclick=()=>document.getElementById("modal").style.display="none";document.getElementById("mClose2").onclick=()=>document.getElementById("modal").style.display="none";
document.getElementById("modal").onclick=e=>{if(e.target.id==="modal")e.currentTarget.style.display="none"};
function init(){days();workout();diet();glucose();subs();history();home();if("serviceWorker"in navigator)navigator.serviceWorker.register("sw.js");}
init();
